### PR TITLE
path to require

### PR DESCRIPTION
**Pull request by ajmalton**
I had to change the require paths, as indicated.

Do you have a different library configuration?

Otherwise, it seems to work, but there are a lot of changes relative to master.

### CODE REVIEW

**Comment by mbab** [comment]
I found "$Bin" redundant here.

**Comment by ajmalton** [comment]
It doesn't matter hugely, if it works for you. But it didn't work for me, running --cgi from the web/ subdirectory.  

The entry points all add $Bin/.. to the ``@INC`` list, but not $Bin itself.  Do you have it in your environment?

**Comment by mbab** [comment]
Of course it is not important but in docker it works from any directory.

**Comment by ajmalton** [comment]
I believe you, but I don't use the Docker wrapper.

I wish I understood how it works without $Bin, because I don't care for FindBin, nor runtime library adjustment in general.

In the Docker wrapper with Apache and mod_cgi, how does horas/ get into the ``@INC``?

**Comment by mbab** [comment]
When run in docker there is `.` in `@INC`.
`use lib ("$Bin/..",".");` or even `use lib ("..",".");` should help.
On other side I doubt if site is run from docker indeed?

**Comment by ajmalton** [comment]
I can't check if this version runs in docker, because I'm not using docker.

If this unified kalendar does what it seems to (I changed the requires to $Bin/ and then it apparently worked for me) then I think it should go into master, ahead of my modernization, because it reduces four programs ({missa,horas}/{kalendar,Ckalendar}.pl) to just one.

But I can't pull it as is, because it doesn't work for me unchanged.

**Pull request merged**
